[[linter]]
code = 'FLAKE8'
include_patterns = ['**/*.py']
exclude_patterns = [
    '.git/**',
    'benchmarks/**',
    'docs/**',
    'examples/**',
    'notebooks/**',
]
command = [
    'python3',
    'tools/lint/flake8_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python3',
    'tools/lint/pip_init.py',
    '--dry-run={{DRYRUN}}',
    'flake8==4.0.1',
    'flake8-breakpoint==1.1.0',
    'flake8-bugbear==22.6.22',
    'flake8-comprehensions==3.10.0',
    'flake8-executable==2.0.4',
    'flake8-pyi==22.5.1',
    'mccabe==0.6.1',
    'pycodestyle==2.8.0',
    'pyflakes==2.4.0',
]

# [[linter]]
# code = 'BLACK'
# include_patterns = [
#     '**/*.py',
# ]
# command = [
#     'python3',
#     'tools/lint/black_linter.py',
#     '--',
#     '@{{PATHSFILE}}'
# ]
# init_command = [
#     'python3',
#     'tools/lint/pip_init.py',
#     '--dry-run={{DRYRUN}}',
#     'black==22.3.0',
# ]
# is_formatter = true
