name: docker-builds

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .circleci/docker/**
      - .github/workflows/docker-builds.yml
  push:
    branches:
      - master
      - main
      - release/*
      - landchecks/*
    paths:
      - .circleci/docker/**
      - .github/workflows/docker-builds.yml
  schedule:
    - cron: 1 3 * * 3

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

env:
  ALPINE_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine
  AWS_DEFAULT_REGION: us-east-1

jobs:
  docker-build:
    runs-on: [self-hosted, linux.2xlarge]
    timeout-minutes: 240
    strategy:
      matrix:
        include:
          - docker-image-name: linux-bionic-py3.8-gcc9
    env:
      DOCKER_IMAGE_BASE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/${{ matrix.docker-image-name }}
    steps:
      - name: Clean workspace
        shell: bash
        run: |
          echo "${GITHUB_WORKSPACE}"
          sudo rm -rf "${GITHUB_WORKSPACE}"
          mkdir "${GITHUB_WORKSPACE}"

      # [see note: pytorch repo ref]
      # deep clone (fetch-depth 0) required for git merge-base
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master

      - name: Setup Linux
        uses: ./.github/actions/setup-linux

      - name: Build docker image
        id: build-docker-image
        uses: ./.github/actions/calculate-docker-image
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        with:
          docker-image-name: ${{ matrix.docker-image-name }}
          always-rebuild: true
          skip_push: false
          force_push: true
          push-ghcr-image: ${{ github.event_name == 'push' }}

      - name: Pull docker image
        uses: pytorch/test-infra/.github/actions/pull-docker-image@main
        with:
          docker-image: ${{ steps.build-docker-image.outputs.docker-image }}

      - name: Chown workspace
        uses: ./.github/actions/chown-workspace
        if: always()

      - name: Teardown Linux
        uses: pytorch/test-infra/.github/actions/teardown-linux@main

        if: always()
