name: periodic-slow-gradcheck-a100

on:
  schedule:
    - cron: 45 0,4,8,12,16,20 * * *
    - cron: 29 8 * * *  # about 1:29am PDT, for mem leak check and rerun disabled tests
  push:
    tags:
      - ciflow/periodic/*
    paths:
      - .github/workflows/periodic-a100.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}-${{ github.event.schedule }}
  cancel-in-progress: true

jobs:
  linux-bionic-cuda11_6-py3-gcc7-slow-gradcheck-build:
    name: linux-bionic-cuda11.6-py3-gcc7-slow-gradcheck
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-cuda11.6-py3-gcc7-slow-gradcheck
      docker-image-name: pytorch-linux-bionic-cuda11.6-cudnn8-py3-gcc7
      cuda-arch-list: '8.0'
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 2, runner: "linux.gcp.a100" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.gcp.a100" },
        ]}

  linux-bionic-cuda11_6-py3-gcc7-slow-gradcheck-test:
    name: linux-bionic-cuda11.6-py3-gcc7-slow-gradcheck
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-cuda11_6-py3-gcc7-slow-gradcheck-build
    with:
      build-environment: linux-bionic-cuda11.6-py3-gcc7-slow-gradcheck
      docker-image: ${{ needs.linux-bionic-cuda11_6-py3-gcc7-slow-gradcheck-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-bionic-cuda11_6-py3-gcc7-slow-gradcheck-build.outputs.test-matrix }}
      timeout-minutes: 300
      use-gha: anything-non-empty-to-use-gha
