name: TorchBench Running with Inductor CI
on:
  pull_request:
    tags:
      - ciflow/dynamo
env:
  PYTHON_VERSION: "3.8"
  # must be consistent with https://github.com/pytorch/benchmark/blob/main/requirements.txt#L19
  NUMPY_VERSION: "1.21.2"
  PR_NUM: ${{ github.event.number }}
  PR_BODY: ${{ github.event.pull_request.body }}
  PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
  PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY }}

jobs:
  run-torchbench:
    # We don't accept running on non-pytorch repos because of security concerns
    # Only run the job when the body contains magic word "RUN_TORCHBENCH:"
    if: ${{ github.repository_owner == 'pytorch' && contains(github.event.pull_request.body, 'RUN_TORCHBENCH:') }}
    runs-on: [self-hosted, bm-runner]
    # Set to 12 hours
    timeout-minutes: 720
    steps:
      - name: Checkout PyTorch
        uses: zhouzhuojie/checkout@05b13c9a0d21f08f6d5e64a1d5042246d13619d9
        with:
          path: pytorch
      - name: Update self-hosted PyTorch
        run: |
          pushd "${HOME}"/pytorch
          git remote prune origin
          git fetch
          popd
      - name: Create conda environment and install deps
        run: |
          conda create -y -n pr-ci python="${PYTHON_VERSION}"
          # shellcheck disable=SC1091
          . "${HOME}"/anaconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          # pin cmake version to 3.22 since 3.23 breaks pytorch build
          # see details at: https://github.com/pytorch/pytorch/issues/74985
          conda install -y numpy="${NUMPY_VERSION}" requests ninja pyyaml mkl mkl-include \
                           setuptools cmake=3.22 cffi typing_extensions boto3 \
                           future six dataclasses pillow pytest tabulate gitpython git-lfs tqdm psutil
      - name: Checkout TorchBench
        uses: zhouzhuojie/checkout@05b13c9a0d21f08f6d5e64a1d5042246d13619d9
        with:
          repository: pytorch/benchmark
          path: benchmark
          lfs: false
          ref: ${{ env.TORCHBENCH_BRANCH }}
      - name: Setup TorchBench branch
        run: |
          # shellcheck disable=SC1091
          . "${HOME}"/anaconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          pushd $HOME/benchmark
          # Pin to specific version to avoid upstream breakages
          git checkout 24b95f2f627bf07a61cefed653419389a7586357
          python install.py
          pip install gym==0.25.2  # workaround issue in 0.26.0
          touch env-v7.key
      - name: Run TorchBench
        run: |
          set -x
          pushd "${HOME}"/pytorch
          PR_MERGE_BASE=$(git merge-base "$PR_BASE_SHA" "$PR_HEAD_SHA")
          popd
          # PR_BODY_FILE=/tmp/pr-body.txt
          # echo "$PR_BODY" > ${PR_BODY_FILE}
          # shellcheck disable=SC1091
          . "${HOME}"/anaconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          python3 pytorch/benchmarks/dynamo/torchbench.py \
                  --ci --accuracy --skip-accuracy-check -d cuda \
                  --inductor --training --float32 \
                  # TESTING
                  --only resnet18 \
                  --output=indcutor_torchbench_training.csv
      - name: TorchBench result check
        run: |
          . "${HOME}"/anaconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          python pytorch/benchmarks/dynamo/check_csv.py -f indcutor_torchbench_training.csv
      - name: Remove conda environment and cleanup
        run: |
          conda env remove --name pr-ci
          rm /tmp/pr-body.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: TorchBench Running with Inductor result
          path: ~/.torchbench/bisection/pr${{ github.event.number }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
