# This is a basic workflow to help you get started with Actions

name: Upload tutorials stat

# Controls when the workflow will run
on:
  pull_request: # DO NOT MERGE
  schedule:
  # Run this once per day.
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-tutorials-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the tutorials repo
        uses: actions/checkout@v3
        with:
          repository: 'pytorch/tutorials'
          path: './tutorials'
          fetch-depth: 0
      - name: Checkout the PyTorch repo
        uses: malfet/checkout@silent-checkout
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          submodules: recursive
          path: pytorch
      - name: Install dependancies
        run: |
          python3 -m pip install boto3==1.26.69 typing==3.7.4.3

      - name: Run the script
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set -x
          python3 pytorch/.github/scripts/get-tutorials-stats.py
