name: Validate Clean binary  images

on:
  push:
    branches:
      main
    paths:
      - .github/workflows/validate-clean-linux-binaries.yml
  pull_request:
    paths:
      - .github/workflows/validate-clean-linux-binaries.yml

env:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_BUILDKIT: 1
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  WITH_PUSH: ${{ github.event_name == 'push' }}

jobs:
  validate-clean-linux-binaries:
    runs-on: ubuntu-20.04-m60
    timeout-minutes: 360
    strategy:
      matrix:
        package_install: ["conda", "pip", "libtorch"]
        # cpu has errors, so they have been left out
        cuda_version: ["11.7", "11.6", "11.3", "10.2", "rocm"]
        python_version: ["3.7", "3.8", "3.9", "3.10"]
    env:
      GPU_ARCH_TYPE: cuda
      GPU_ARCH_VERSION: ${{ matrix.cuda_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
    steps:
      - name: Checkout PyTorch builder
        uses: actions/checkout@v2
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python_version }}
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: testenv
      - name: Check nvidia smi
        run: |
          nvidia-smi
      - name: Install pytorch and smoke test
        env:
          ENV_NAME: env-${{ matrix.package_install }}-${{ github.run_id }}
          CUDA_VER: ${{ matrix.cuda_version }}
          PACKAGE_VER: ${{matrix.package_install}}
        run: |
          set -ex
          
          # install conda with cuda -- tested for all
          if [ ${PACKAGE_VER} == 'conda' ]; then
            conda create -yp ${ENV_NAME} python=${PYTHON_VERSION} numpy
            case $CUDA_VER in
              ("cpu") { conda install pytorch torchvision torchaudio cpuonly -c pytorch;
                        conda run --cwd /tmp -p ${ENV_NAME} python3 -c "import torch;y=torch.randn([3,5]);print(y);"; }
                      ;;
              ("10.2") { conda install -p ${ENV_NAME} pytorch torchvision torchaudio cudatoolkit=${CUDA_VER} -c pytorch;
                        conda run -p ${ENV_NAME} python3 ./test/smoke_test/smoke_test.py;}
                       ;;
              ("11.3") { conda install -p ${ENV_NAME} pytorch torchvision torchaudio cudatoolkit=${CUDA_VER} -c pytorch;
                        conda run -p ${ENV_NAME} python3 ./test/smoke_test/smoke_test.py; }
                       ;;
              ("11.6") { conda install -p ${ENV_NAME} pytorch torchvision torchaudio cudatoolkit=${CUDA_VER} -c pytorch -c conda-forge;
                        conda run -p ${ENV_NAME} python3 ./test/smoke_test/smoke_test.py; }
                       ;;
              ("11.7") { conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch-nightly -c nvidia;
                        conda run -p ${ENV_NAME} python3 ./test/smoke_test/smoke_test.py; }
                       ;;
             (*) echo "No binary available"
                   ;;
              esac
          fi
                    
          # install pip -- tested for all cuda except cpu -- takes a very long time
          if [ ${PACKAGE_VER} == 'pip' ]; then
            apt-get install python3-pip -y
            case $CUDA_VER in
              ("rocm") { python3 -m pip3 install torch torchvision torchaudio --extra-index-url "https://download.pytorch.org/whl/rocm5.1.1";
                       python3 ./test/smoke_test/smoke_test.py; }
                       ;;
              ("cpu") { python3 -m pip3 install torch torchvision torchaudio --extra-index-url "https://download.pytorch.org/whl/cpu";
                       python3 ./test/smoke_test/smoke_test.py; }
                       ;;
              ("10.2") { python3 -m pip3 install torch torchvision torchaudio;
                       python3 ./test/smoke_test/smoke_test.py; }
                       ;;
              ("11.3") { python3 -m pip3 install torch torchvision torchaudio --extra-index-url "https://download.pytorch.org/whl/cu113";
                       python3 ./test/smoke_test/smoke_test.py; }
                       ;;
              ("11.6") { python3 -m pip3 install torch torchvision torchaudio --extra-index-url "https://download.pytorch.org/whl/cu116";
                       python3 ./test/smoke_test/smoke_test.py; }
                       ;;
              ("11.7") { python3 -m pip3 install --pre torch torchvision torchaudio --extra-index-url "https://download.pytorch.org/whl/nightly/cu117";
                       python3 ./test/smoke_test/smoke_test.py; }
                       ;;
             (*) echo "No binary available"
                   ;;
              esac
          fi          
                    
          # install libtorch -- tested for all cuda except cpu and 11.7
          if [ ${PACKAGE_VER} == 'libtorch' ]; then
            apt-get install unzip -y
            case ${CUDA_VER} in
              ("rocm") { wget https://download.pytorch.org/libtorch/rocm5.1.1/libtorch-cxx11-abi-shared-with-deps-1.12.1%2Brocm5.1.1.zip;
                       unzip libtorch-cxx11-abi-shared-with-deps-1.12.1+rocm5.1.1; }
                       ;;
              ("cpu") { wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.12.1%2Bcpu.zip;
                      unzip libtorch-cxx11-abi-shared-with-deps-1.12.1+cpu; }
                      ;;
              ("10.2") { wget https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.12.1%2Bcu102.zip;
                       unzip libtorch-cxx11-abi-shared-with-deps-1.12.1+cu102; }
                       ;;
              ("11.3") { wget https://download.pytorch.org/libtorch/cu113/libtorch-cxx11-abi-shared-with-deps-1.12.1%2Bcu113.zip;
                       unzip libtorch-cxx11-abi-shared-with-deps-1.12.1+cu113; }
                       ;;
              ("11.6") { wget https://download.pytorch.org/libtorch/cu116/libtorch-cxx11-abi-shared-with-deps-1.12.1%2Bcu116.zip;
                       unzip libtorch-cxx11-abi-shared-with-deps-1.12.1+cu116; }
                       ;;
              (*) echo "No binary available"
                  ;;
              esac
          fi
